service: serverless-todo-app

plugins:
  - serverless-iam-roles-per-function

frameworkVersion: '3.24.1'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    ATTACHMENT_S3_BUCKET: vuongbucket
    SIGNED_URL_EXPIRATION: 300 # URL expiration time in seconds (5 minutes)

functions:

  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  # TODO: Configure this function
  getTodos:
    handler: src/lambda/http/getTodos.handler
    events:
      - http:
          method: get
          path: todos
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.todosTable}

  # TODO: Configure this function
  createTodo:
    handler: src/lambda/http/createTodos.handler
    events:
      - http:
          method: post
          path: todos
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:REGION:ACCOUNT_ID:table/TABLE_NAME

  # TODO: Configure this function
  updateTodo:
    handler: src/lambda/http/updateTodo.handler
    events:
      - http:
          method: put
          path: todos/{todoId}
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:REGION:ACCOUNT_ID:table/TABLE_NAME

  # TODO: Configure this function
  deleteTodo:
    handler: src/lambda/http/deleteTodo.handler
    events:
      - http:
          method: delete
          path: todos/{todoId}
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: arn:aws:dynamodb:REGION:ACCOUNT_ID:table/TABLE_NAME

  # TODO: Configure this function
  generateUploadUrl:
    handler: src/lambda/http/generateUploadUrl.handler
    events:
      - http:
          method: get
          path: todos/{todoId}/attachment
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource: arn:aws:s3:::vuongbucket/* 

resources:
  Resources:
    # TODO: Add any necessary AWS resources